#!/bin/sh -e

GITHUB_TOKEN="";

REPO_DOMAIN="https://api.github.com/repos";
REPO_OWNER="";
REPO_NAME="";
API_ENDPOINT="contents"; # GitHub Doc: https://docs.github.com/en/rest/repos/contents
REPO_PATH="";

REPO_URL="${REPO_DOMAIN}/${REPO_OWNER}/${REPO_NAME}/${API_ENDPOINT}/${REPO_PATH}";

JSON_PAYLOAD='{
	"message": "my commit message",
	"content": "bXkgbmV3IGZpbGUgY29udGVudHM="
}'; # "content" is a base64 encoded string. It will decode to "my new file contents".

main() 
{
	curl -L -# \
  		-X PUT \
  		-w '\nhttp_code=%{stderr}%{http_code}\n%{stdout}\n' \
  		-H "Accept: application/vnd.github+json" \
  		-H "Authorization: Bearer ${GITHUB_TOKEN}" \
  		-H "X-GitHub-Api-Version: 2022-11-28" \
  		-d "${JSON_PAYLOAD}" \
  		--url "${REPO_URL}"; # 1>/dev/null
	
	printf "Curl Exit Code: $?"; 
		# Details on Exit codes are here: https://curl.se/docs/manpage.html
}; main "$@"
